name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: clone submodule
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: make
      - name: Run tests
        run: make test
